// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Head: typeof import('@inertiajs/inertia-vue3')['Head']
    JetActionMessage: typeof import('./../../../../../../resources/scripts/components/Jetstream/ActionMessage.vue')['default']
    JetActionSection: typeof import('./../../../../../../resources/scripts/components/Jetstream/ActionSection.vue')['default']
    JetApplicationLogo: typeof import('./../../../../../../resources/scripts/components/Jetstream/ApplicationLogo.vue')['default']
    JetApplicationMark: typeof import('./../../../../../../resources/scripts/components/Jetstream/ApplicationMark.vue')['default']
    JetAuthenticationCard: typeof import('./../../../../../../resources/scripts/components/Jetstream/AuthenticationCard.vue')['default']
    JetAuthenticationCardLogo: typeof import('./../../../../../../resources/scripts/components/Jetstream/AuthenticationCardLogo.vue')['default']
    JetBanner: typeof import('./../../../../../../resources/scripts/components/Jetstream/Banner.vue')['default']
    JetButton: typeof import('./../../../../../../resources/scripts/components/Jetstream/Button.vue')['default']
    JetCheckbox: typeof import('./../../../../../../resources/scripts/components/Jetstream/Checkbox.vue')['default']
    JetConfirmationModal: typeof import('./../../../../../../resources/scripts/components/Jetstream/ConfirmationModal.vue')['default']
    JetConfirmsPassword: typeof import('./../../../../../../resources/scripts/components/Jetstream/ConfirmsPassword.vue')['default']
    JetDangerButton: typeof import('./../../../../../../resources/scripts/components/Jetstream/DangerButton.vue')['default']
    JetDialogModal: typeof import('./../../../../../../resources/scripts/components/Jetstream/DialogModal.vue')['default']
    JetDropdown: typeof import('./../../../../../../resources/scripts/components/Jetstream/Dropdown.vue')['default']
    JetDropdownLink: typeof import('./../../../../../../resources/scripts/components/Jetstream/DropdownLink.vue')['default']
    JetFormSection: typeof import('./../../../../../../resources/scripts/components/Jetstream/FormSection.vue')['default']
    JetInput: typeof import('./../../../../../../resources/scripts/components/Jetstream/Input.vue')['default']
    JetInputError: typeof import('./../../../../../../resources/scripts/components/Jetstream/InputError.vue')['default']
    JetLabel: typeof import('./../../../../../../resources/scripts/components/Jetstream/Label.vue')['default']
    JetModal: typeof import('./../../../../../../resources/scripts/components/Jetstream/Modal.vue')['default']
    JetNavLink: typeof import('./../../../../../../resources/scripts/components/Jetstream/NavLink.vue')['default']
    JetResponsiveNavLink: typeof import('./../../../../../../resources/scripts/components/Jetstream/ResponsiveNavLink.vue')['default']
    JetSecondaryButton: typeof import('./../../../../../../resources/scripts/components/Jetstream/SecondaryButton.vue')['default']
    JetSectionBorder: typeof import('./../../../../../../resources/scripts/components/Jetstream/SectionBorder.vue')['default']
    JetSectionTitle: typeof import('./../../../../../../resources/scripts/components/Jetstream/SectionTitle.vue')['default']
    JetValidationErrors: typeof import('./../../../../../../resources/scripts/components/Jetstream/ValidationErrors.vue')['default']
    JetWelcome: typeof import('./../../../../../../resources/scripts/components/Jetstream/Welcome.vue')['default']
    Link: typeof import('@inertiajs/inertia-vue3')['Link']
  }
}

export {}
