// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./../components/ActionMessage.vue')['default']
    ActionSection: typeof import('./../components/ActionSection.vue')['default']
    ApplicationLogo: typeof import('./../components/ApplicationLogo.vue')['default']
    ApplicationMark: typeof import('./../components/ApplicationMark.vue')['default']
    AuthenticationCard: typeof import('./../components/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./../components/AuthenticationCardLogo.vue')['default']
    Banner: typeof import('./../components/Banner.vue')['default']
    Checkbox: typeof import('./../components/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./../components/ConfirmationModal.vue')['default']
    ConfirmsPassword: typeof import('./../components/ConfirmsPassword.vue')['default']
    DangerButton: typeof import('./../components/DangerButton.vue')['default']
    DialogModal: typeof import('./../components/DialogModal.vue')['default']
    Dropdown: typeof import('./../components/Dropdown.vue')['default']
    DropdownLink: typeof import('./../components/DropdownLink.vue')['default']
    FormSection: typeof import('./../components/FormSection.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    InputError: typeof import('./../components/InputError.vue')['default']
    InputLabel: typeof import('./../components/InputLabel.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    Modal: typeof import('./../components/Modal.vue')['default']
    NavLink: typeof import('./../components/NavLink.vue')['default']
    PrimaryButton: typeof import('./../components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./../components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./../components/SecondaryButton.vue')['default']
    SectionBorder: typeof import('./../components/SectionBorder.vue')['default']
    SectionTitle: typeof import('./../components/SectionTitle.vue')['default']
    TextInput: typeof import('./../components/TextInput.vue')['default']
    Welcome: typeof import('./../components/Welcome.vue')['default']
  }
}
